### ISSUE TITLE
Rethink data organization

### ISSUE THREAD

**Issue by Gjum** [Gjum/logalyzer-mc#5]
The current way to store join/left events and online durations is inefficient for the targeted use.
- Scanfiles contain three types of information, ranging from raw join/left times to analyzed online times.
- Files represent daily data, not server runtime dependent data. This makes problems like #2 possible.

**Comment by HarHarLinks** [comment]
Data should only be saved if it is going to be used further.
We need:
- onlinetime per slot and user for histogram
- still online users for being able to prevent issues like #2. Could also be used to indicate who is currently active.
