### ISSUE TITLE
UnicodeEncodeError in scan.py drawHistogram()

### ISSUE THREAD

**Issue by HarHarLinks** [Gjum/logalyzer-mc#6]
Traceback (most recent call last):
  File "scan.py", line 174, in <module>
    processor.drawHistogram()
  File "scan.py", line 152, in drawHistogram
    print('%-16s%s' % (player, line))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 56-57: ordinal not in range(256)

**Comment by Gjum** [comment]
Fixed in d3f4753
