### ISSUE TITLE
punchcardCustom does not show cells at end of range if empty

### ISSUE THREAD

**Issue by HarHarLinks** [Gjum/logalyzer-mc#9]

**Comment by HarHarLinks** [comment]
fixed in 26138961c7e740d9d1ea347bc57bd755ec49a64a

**Comment by HarHarLinks** [comment]
undone buggy workaround, has to be done in LogProcessor.py/getPunchcard

**Comment by Gjum** [comment]
I would prefer switching to a continuous graph per session, starting when a player logs in until logging out.
Punchcards could still be used for representing total player activity per hour, maybe also per weekday (which is the intended use of punchcards anyway).
